apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: okteto-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-container
        image: okteto/go-getting-started:hello-world
        ports:
        - containerPort: 8080