apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  namespace: okteto-go-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: go-7f000001.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-app-service
            port:
              number: 80